const crypto=require('crypto');
const Payment=require('../models/Payment');
const Wallet=require('../models/Wallet');

function secret(){const key=String(process.env.PAYSTACK_SECRET_KEY||'').trim();if(!key)throw Object.assign(new Error('Paystack is not configured on the server'),{statusCode:503});if(!/^sk_(test|live)_/.test(key))throw Object.assign(new Error('PAYSTACK_SECRET_KEY is invalid'),{statusCode:503});return key;}
function mode(){const key=String(process.env.PAYSTACK_SECRET_KEY||'').trim();return key.startsWith('sk_live_')?'live':key.startsWith('sk_test_')?'test':'unconfigured';}
async function request(path,options={}){const controller=new AbortController();const timeout=setTimeout(()=>controller.abort(),30000);try{const response=await fetch(`https://api.paystack.co${path}`,{...options,signal:options.signal||controller.signal,headers:{Authorization:`Bearer ${secret()}`,'Content-Type':'application/json',...(options.headers||{})}});const raw=await response.text();let body={};try{body=raw?JSON.parse(raw):{}}catch{body={status:false,message:'Invalid response from Paystack'}}if(!response.ok||!body.status){const error=new Error(body.message||`Paystack request failed (${response.status})`);error.statusCode=response.status===400?400:response.status===429?429:response.status===401||response.status===403?502:502;error.paystackResponse=body;throw error;}return body;}catch(e){if(e?.name==='AbortError')throw Object.assign(new Error('Paystack request timed out. Please try again.'),{statusCode:504});throw e}finally{clearTimeout(timeout)}}
function newReference(){return `KO-WALLET-${Date.now()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;}
async function initializeWalletTopup({user,amount}){const email=String(user?.email||'').trim().toLowerCase();if(!email)throw Object.assign(new Error('Add an email address before funding your wallet'),{statusCode:400});const numeric=Number(amount);if(!Number.isInteger(numeric)||numeric<100)throw Object.assign(new Error('Minimum wallet funding amount is ₦100'),{statusCode:400});const reference=newReference();const callbackBase=String(process.env.CLIENT_URL||'http://localhost:5173').replace(/\/$/,'');const body=await request('/transaction/initialize',{method:'POST',body:JSON.stringify({email,amount:String(numeric*100),currency:'NGN',reference,callback_url:`${callbackBase}/wallet/paystack/callback`,metadata:{purpose:'wallet_topup',userId:String(user._id),phone:user.phone||''}})});await Payment.create({user:user._id,reference,accessCode:body.data.access_code,amount:numeric,currency:'NGN',status:'initialized',metadata:{email,phone:user.phone||''}});return{authorizationUrl:body.data.authorization_url,accessCode:body.data.access_code,reference};}
async function verifyReference(reference){const clean=String(reference||'').trim();if(!clean)throw Object.assign(new Error('Payment reference is required'),{statusCode:400});return request(`/transaction/verify/${encodeURIComponent(clean)}`,{method:'GET'});}
async function fulfillWalletTopup(payment,data){if(!payment)throw Object.assign(new Error('Payment record not found'),{statusCode:404});if(!data)throw Object.assign(new Error('Paystack transaction data is required'),{statusCode:400});if(String(data.reference)!==String(payment.reference))throw Object.assign(new Error('Payment reference mismatch'),{statusCode:400});if(data.status!=='success'){await Payment.updateOne({_id:payment._id},{$set:{status:['failed','abandoned','reversed'].includes(data.status)?data.status:'pending',gatewayResponse:data.gateway_response||''}});return{credited:false,status:data.status};}if(Number(data.amount)!==Math.round(Number(payment.amount)*100))throw Object.assign(new Error('Verified payment amount does not match the wallet top-up'),{statusCode:400});if(String(data.currency||'NGN').toUpperCase()!=='NGN')throw Object.assign(new Error('Unexpected payment currency'),{statusCode:400});const wallet=await Wallet.findOneAndUpdate({user:payment.user,'transactions.reference':{$ne:payment.reference}},{$inc:{balance:payment.amount},$push:{transactions:{type:'credit',amount:payment.amount,description:'Paystack wallet funding',reference:payment.reference,provider:'paystack',status:'success'}}},{new:true});const existing=wallet||await Wallet.findOne({user:payment.user});if(!existing)throw new Error('Wallet not found');await Payment.updateOne({_id:payment._id},{$set:{status:'success',channel:data.channel||'',gatewayResponse:data.gateway_response||'',paystackTransactionId:String(data.id||''),paidAt:data.paid_at?new Date(data.paid_at):new Date(),creditedAt:new Date()}});return{credited:!!wallet,status:'success',wallet:existing};}
function validWebhookSignature(rawBody,signature){if(rawBody==null||!signature)return false;const raw=Buffer.isBuffer(rawBody)?rawBody:typeof rawBody==='string'?Buffer.from(rawBody):null;if(!raw)return false;const hash=crypto.createHmac('sha512',secret()).update(raw).digest('hex');const a=Buffer.from(hash);const b=Buffer.from(String(signature).trim().toLowerCase());return a.length===b.length&&crypto.timingSafeEqual(a,b);}
let bankCache=null,bankCacheExpiresAt=0;const BANK_CACHE_TTL=6*60*60*1000;
async function listNigerianBanks({forceRefresh=false}={}){if(!forceRefresh&&bankCache&&Date.now()<bankCacheExpiresAt)return{status:true,data:bankCache};const all=[];for(let page=1;page<=10;page++){const r=await request(`/bank?country=nigeria&currency=NGN&type=nuban&perPage=100&page=${page}`,{method:'GET'});const rows=Array.isArray(r.data)?r.data:[];all.push(...rows);if(rows.length<100)break;}const map=new Map();for(const b of all){if(!b||b.active===false||b.is_deleted===true)continue;const name=String(b.name||'').trim(),code=String(b.code||'').trim();if(name&&code)map.set(`${code}|${name}`.toLowerCase(),{name,code,slug:b.slug||'',type:b.type||'nuban',country:'Nigeria',currency:'NGN',active:true});}bankCache=[...map.values()].sort((a,b)=>a.name.localeCompare(b.name));bankCacheExpiresAt=Date.now()+BANK_CACHE_TTL;return{status:true,data:bankCache};}
async function resolveBankAccount({accountNumber,bankCode}){const account=String(accountNumber||'').replace(/\s+/g,'');const code=String(bankCode||'').trim();if(!/^\d{10}$/.test(account))throw Object.assign(new Error('Account number must be exactly 10 digits'),{statusCode:400});if(!code)throw Object.assign(new Error('Bank selection is required'),{statusCode:400});return request(`/bank/resolve?account_number=${encodeURIComponent(account)}&bank_code=${encodeURIComponent(code)}`,{method:'GET'});}
async function createTransferRecipient({accountName,accountNumber,bankCode,currency='NGN'}){const name=String(accountName||'').trim(),account=String(accountNumber||'').replace(/\s+/g,''),code=String(bankCode||'').trim();if(!name)throw Object.assign(new Error('Account name is required'),{statusCode:400});if(!/^\d{10}$/.test(account))throw Object.assign(new Error('Account number must be exactly 10 digits'),{statusCode:400});if(!code)throw Object.assign(new Error('Bank selection is required'),{statusCode:400});return request('/transferrecipient',{method:'POST',body:JSON.stringify({type:'nuban',name,account_number:account,bank_code:code,currency:String(currency).toUpperCase()})});}
function newTransferReference(){return `KO-TRANSFER-${Date.now()}-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;}
async function initiateTransfer({amount,recipientCode,reference,reason='Kaduna Only wallet withdrawal'}){const numeric=Number(amount);if(!Number.isInteger(numeric)||numeric<=0)throw Object.assign(new Error('Transfer amount must be a positive whole naira amount'),{statusCode:400});if(!recipientCode||!reference)throw Object.assign(new Error('Transfer recipient and reference are required'),{statusCode:400});return request('/transfer',{method:'POST',body:JSON.stringify({source:'balance',amount:numeric*100,recipient:recipientCode,reference,reason})});}
async function verifyTransfer(reference){const clean=String(reference||'').trim();if(!clean)throw Object.assign(new Error('Transfer reference is required'),{statusCode:400});return request(`/transfer/verify/${encodeURIComponent(clean)}`,{method:'GET'});}
module.exports={initializeWalletTopup,verifyReference,fulfillWalletTopup,validWebhookSignature,listNigerianBanks,resolveBankAccount,createTransferRecipient,initiateTransfer,verifyTransfer,newTransferReference,mode};
