const DriverProfile=require('../models/DriverProfile');
const Trip=require('../models/Trip');
const Wallet=require('../models/Wallet');
const {emitDriverLocation}=require('../realtime');
const activeStatuses=['DRIVER_ASSIGNED','DRIVER_ARRIVING','DRIVER_ARRIVED','TRIP_STARTED'];
async function getMe(req,res,next){try{const p=await DriverProfile.findOne({user:req.user._id}).populate('user','fullName phone email role status');if(!p)return res.status(404).json({success:false,message:'Driver profile not found'});res.json({success:true,data:{profile:p}})}catch(e){next(e)}}
async function dashboard(req,res,next){try{const p=await DriverProfile.findOne({user:req.user._id}).populate('user','fullName phone email role status');if(!p)return res.status(404).json({success:false,message:'Driver profile not found'});const [wallet,active,completed,recent]=await Promise.all([Wallet.findOne({user:req.user._id}),Trip.findOne({driver:req.user._id,status:{$in:activeStatuses}}).populate('rider','fullName phone'),Trip.countDocuments({driver:req.user._id,status:'TRIP_COMPLETED'}),Trip.find({driver:req.user._id}).populate('rider','fullName phone').sort({createdAt:-1}).limit(5)]);res.json({success:true,data:{profile:p,wallet:{balance:wallet?.balance||0},activeTrip:active||null,completedTrips:completed,recentTrips:recent}})}catch(e){next(e)}}
async function updateMe(req,res,next){try{const fields=['vehicleType','vehicleModel','vehicleColor','plateNumber'];const u={};for(const k of fields)if(req.body[k]!==undefined)u[k]=typeof req.body[k]==='string'?req.body[k].trim():req.body[k];const p=await DriverProfile.findOneAndUpdate({user:req.user._id},{$set:u},{returnDocument:'after',runValidators:true}).populate('user','fullName phone email role status');if(!p)return res.status(404).json({success:false,message:'Driver profile not found'});res.json({success:true,data:{profile:p}})}catch(e){next(e)}}
async function setOnline(req,res,next){try{const online=!!req.body.online;const p=await DriverProfile.findOne({user:req.user._id});if(!p)return res.status(404).json({success:false,message:'Driver profile not found'});if(p.verificationStatus!=='approved')return res.status(403).json({success:false,message:'Driver must be approved before going online'});if(!online){const active=await Trip.exists({driver:req.user._id,status:{$in:activeStatuses}});if(active)return res.status(409).json({success:false,message:'You cannot go offline during an active trip'});}p.online=online;await p.save();res.json({success:true,data:{online:p.online}})}catch(e){next(e)}}
async function location(req,res,next){try{const latitude=Number(req.body.latitude),longitude=Number(req.body.longitude),accuracy=req.body.accuracy==null?undefined:Number(req.body.accuracy);if(!Number.isFinite(latitude)||latitude< -90||latitude>90||!Number.isFinite(longitude)||longitude< -180||longitude>180)return res.status(400).json({success:false,message:'Valid latitude and longitude are required'});const p=await DriverProfile.findOneAndUpdate({user:req.user._id,verificationStatus:'approved'},{$set:{location:{latitude,longitude,accuracy,updatedAt:new Date()}}},{returnDocument:'after'});if(!p)return res.status(403).json({success:false,message:'Approved driver profile required'});const active=await Trip.findOne({driver:req.user._id,status:{$in:activeStatuses}}).select('_id rider');if(active)emitDriverLocation({driverId:req.user._id,riderId:active.rider,tripId:active._id,location:p.location});res.json({success:true,data:{location:p.location}})}catch(e){next(e)}}
async function list(req,res,next){try{const p=await DriverProfile.find().populate('user','fullName phone email role status').sort({createdAt:-1});res.json({success:true,data:{drivers:p}})}catch(e){next(e)}}
async function verify(req,res,next){try{const allowed=['pending','approved','rejected','suspended'];if(!allowed.includes(req.body.status))return res.status(400).json({success:false,message:'Invalid verification status'});const p=await DriverProfile.findByIdAndUpdate(req.params.id,{$set:{verificationStatus:req.body.status,online:false}},{returnDocument:'after',runValidators:true}).populate('user','fullName phone email role status');if(!p)return res.status(404).json({success:false,message:'Driver profile not found'});res.json({success:true,data:{profile:p}})}catch(e){next(e)}}
module.exports={getMe,dashboard,updateMe,setOnline,location,list,verify};
