import React,{useEffect,useState}from'react';
import{Wallet as WalletIcon,ArrowDownLeft,ArrowUpRight,Plus,ShieldCheck,ExternalLink,RefreshCw}from'lucide-react';
import{RiderLayout,PageHeader,api,formatMoney,useApp,Notice,Button}from'../../shared';
export default function WalletPage(){
  const{notify,user}=useApp();const[w,setW]=useState({balance:0,transactions:[]});const[mode,setMode]=useState('unconfigured');const[amount,setAmount]=useState('5000');const[busy,setBusy]=useState(false);
  async function load(){try{const r=await api('/wallet');setW(r.data.wallet||{balance:0,transactions:[]});setMode(r.data.paystackMode||'unconfigured')}catch(e){notify(e.message)}}useEffect(()=>{load()},[]);
  async function fund(){const value=Number(amount);if(!Number.isFinite(value)||value<100)return notify({title:'Invalid amount',message:'Enter at least ₦100.'});if(!user?.email)return notify({title:'Email required',message:'Add an email address in your Profile before funding your wallet.'});setBusy(true);try{const r=await api('/wallet/paystack/initialize',{method:'POST',body:JSON.stringify({amount:value})});window.location.assign(r.data.authorizationUrl)}catch(e){notify(e.message);setBusy(false)}}
  return <RiderLayout><PageHeader title="Wallet" subtitle="Fund your Kaduna Only wallet securely with Paystack." action={<Button onClick={load} variant="secondary"><RefreshCw size={16}/>Refresh</Button>}/><div className="wallet-hero"><div><span>Available Balance</span><strong>{formatMoney(w.balance)}</strong><small>Verified Paystack payments are credited by the server.</small></div><WalletIcon size={42}/></div>{mode==='test'&&<Notice title="Paystack Test Mode" text="No real money is charged while your Paystack integration uses test keys."/>}{mode==='unconfigured'&&<Notice title="Paystack not configured" text="Add PAYSTACK_SECRET_KEY to the backend .env before attempting wallet funding." tone="warning"/>}<div className="panel wallet-fund-panel"><div className="panel-title"><div><h3>Add money</h3><p>Payment is initialized and verified by Kaduna Only's backend.</p></div><ShieldCheck size={24}/></div><label className="wallet-amount-label">Amount (NGN)<input type="number" min="100" step="100" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="5000"/></label><div className="wallet-quick">{[2000,5000,10000,20000].map(v=><button type="button" key={v} onClick={()=>setAmount(String(v))}>{formatMoney(v)}</button>)}</div><Button full onClick={fund} disabled={busy||mode==='unconfigured'}><Plus size={17}/>{busy?'Opening Paystack…':'Fund Wallet with Paystack'}<ExternalLink size={15}/></Button>{!user?.email&&<p className="muted">Add an email address in <a href="/profile">Profile</a> before funding your wallet.</p>}</div><div className="panel"><h3>Recent transactions</h3>{w.transactions?.length?w.transactions.slice().reverse().slice(0,20).map((x,i)=><div className="transaction" key={`${x.reference||i}-${x.createdAt}`}><span className={x.type==='credit'?'credit':'debit'}>{x.type==='credit'?<ArrowDownLeft/>:<ArrowUpRight/>}</span><div><b>{x.description}</b><small>{new Date(x.createdAt).toLocaleString('en-NG')}{x.reference?` · ${x.reference}`:''}</small></div><strong>{x.type==='credit'?'+':'-'}{formatMoney(x.amount)}</strong></div>):<p className="muted">No transactions yet.</p>}</div></RiderLayout>
}
