import React,{useEffect}from'react';
import{MapContainer,TileLayer,Polyline,CircleMarker,Popup,useMap,Marker}from'react-leaflet';
import L from'leaflet';
const KADUNA=[10.5105,7.4165];
const valid=p=>p&&Number.isFinite(Number(p.lat))&&Number.isFinite(Number(p.lng));
const validDriver=p=>p&&Number.isFinite(Number(p.latitude))&&Number.isFinite(Number(p.longitude));
const driverIcon=L.divIcon({className:'ko-driver-marker',html:'<div class="ko-driver-pulse"><span>🚗</span></div>',iconSize:[42,42],iconAnchor:[21,21]});
function Fit({pickup,destination,driver,route,followDriver}){const map=useMap();useEffect(()=>{if(followDriver&&validDriver(driver)){map.panTo([Number(driver.latitude),Number(driver.longitude)],{animate:true,duration:.7});return}const pts=[];if(route?.coordinates)route.coordinates.forEach(([lng,lat])=>pts.push([lat,lng]));else{if(valid(pickup))pts.push([Number(pickup.lat),Number(pickup.lng)]);if(valid(destination))pts.push([Number(destination.lat),Number(destination.lng)])}if(validDriver(driver))pts.push([Number(driver.latitude),Number(driver.longitude)]);if(pts.length>1)map.fitBounds(pts,{padding:[40,40],maxZoom:16});else if(pts.length===1)map.setView(pts[0],15)},[map,pickup?.lat,pickup?.lng,destination?.lat,destination?.lng,driver?.latitude,driver?.longitude,route,followDriver]);return null}
export default function LiveMap({pickup,destination,driverLocation,routeGeometry,liveRouteGeometry,height=330,followDriver=false}){const route=routeGeometry?.coordinates?.map(([lng,lat])=>[lat,lng])||[];const liveRoute=liveRouteGeometry?.coordinates?.map(([lng,lat])=>[lat,lng])||[];return <div className="leaflet-shell" style={{height}}><MapContainer center={valid(pickup)?[Number(pickup.lat),Number(pickup.lng)]:KADUNA} zoom={12} scrollWheelZoom style={{height:'100%',width:'100%'}}><TileLayer attribution='&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors' url="https://tile.openstreetmap.org/{z}/{x}/{y}.png"/>{route.length>1&&<Polyline positions={route} pathOptions={{weight:4,opacity:.34,dashArray:'9 8'}}/>}{liveRoute.length>1&&<Polyline positions={liveRoute} pathOptions={{weight:6,opacity:.9}}/>}{valid(pickup)&&<CircleMarker center={[Number(pickup.lat),Number(pickup.lng)]} radius={9} pathOptions={{fillOpacity:1}}><Popup>Pickup: {pickup.label}</Popup></CircleMarker>}{valid(destination)&&<CircleMarker center={[Number(destination.lat),Number(destination.lng)]} radius={9} pathOptions={{fillOpacity:1}}><Popup>Destination: {destination.label}</Popup></CircleMarker>}{validDriver(driverLocation)&&<Marker position={[Number(driverLocation.latitude),Number(driverLocation.longitude)]} icon={driverIcon}><Popup>Driver live location<br/>{driverLocation.updatedAt?`Updated ${new Date(driverLocation.updatedAt).toLocaleTimeString()}`:''}</Popup></Marker>}<Fit pickup={pickup} destination={destination} driver={driverLocation} route={liveRouteGeometry||routeGeometry} followDriver={followDriver}/></MapContainer></div>}
