import React,{useEffect,useState}from'react';
import{Link,useNavigate}from'react-router-dom';
import{Power,Car,Wallet,Star,ClipboardList,Navigation,RefreshCw,ArrowRight,Radio}from'lucide-react';
import{DriverLayout,PageHeader,Stat,Badge,api,useApp,formatMoney,Button,Notice}from'../../shared';
export default function DriverDashboard(){
  const{notify,socket,alertsEnabled}=useApp();const nav=useNavigate();const[p,setP]=useState(null);const[trips,setTrips]=useState([]);const[available,setAvailable]=useState([]);const[wallet,setWallet]=useState(0);const[loading,setLoading]=useState(true);const[gps,setGps]=useState('idle');const[accepting,setAccepting]=useState(null);
  async function load(silent=false){if(!silent)setLoading(true);try{const[a,b,c]=await Promise.all([api('/drivers/dashboard'),api('/trips'),api('/trips/available').catch(()=>({data:{trips:[]}}))]);setP(a.data.profile);setTrips(b.data.trips||[]);setAvailable(c.data.trips||[]);setWallet(a.data.wallet?.balance||0)}catch(e){notify(e.message)}finally{if(!silent)setLoading(false)}}
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!socket)return;const refresh=()=>load(true);socket.on('trip:new',refresh);socket.on('trip:taken',refresh);socket.on('trip:updated',refresh);return()=>{socket.off('trip:new',refresh);socket.off('trip:taken',refresh);socket.off('trip:updated',refresh)}},[socket]);
  useEffect(()=>{if(!p?.online||!socket||!navigator.geolocation){setGps('idle');return}setGps('requesting');const id=navigator.geolocation.watchPosition(pos=>{setGps('live');socket.emit('driver:location',{latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy},ack=>{if(ack&&!ack.success)setGps('error')})},()=>setGps('error'),{enableHighAccuracy:true,maximumAge:5000,timeout:15000});return()=>navigator.geolocation.clearWatch(id)},[p?.online,socket]);
  async function toggle(){try{const r=await api('/drivers/me/online',{method:'PATCH',body:JSON.stringify({online:!p.online})});setP({...p,online:r.data.online});socket?.emit('driver:availability',{},()=>{});notify(r.data.online?'You are now online':'You are now offline')}catch(e){notify(e.message)}}
  async function accept(tripId){if(accepting)return;setAccepting(tripId);try{const r=await api(`/trips/${tripId}/accept`,{method:'POST'});notify('Ride accepted successfully');setAvailable(prev=>prev.filter(t=>t._id!==tripId));nav(`/driver/trip/${r.data.trip._id}`)}catch(e){notify(e.message);await load(true)}finally{setAccepting(null)}}
  if(loading)return <DriverLayout><div className="panel loading">Loading dashboard…</div></DriverLayout>;
  return <DriverLayout><PageHeader title="Driver Dashboard" subtitle="Manage rides, earnings and live driver availability." action={<Button onClick={()=>load()} variant="secondary"><RefreshCw size={16}/>Refresh</Button>}/>{p.verificationStatus==='approved'&&!alertsEnabled&&<Notice title="Enable ride alerts" text="Tap the bell icon at the top of the app to enable browser notifications. Incoming ride requests also use an in-app sound alert." tone="warning"/>}{p.verificationStatus!=='approved'&&<Notice title="Approval required" text="Your account must be approved by an administrator before you can go online." tone="warning"/>}<div className="status-card"><div className={`status-dot ${p.online?'online':''}`}/><div><span>Driver Status</span><h2>{p.online?'You are Online':'You are Offline'}</h2><p>{p.online?'New matching ride requests arrive automatically.':'Go online when you are ready to drive.'}</p>{p.online&&<small><Radio size={13}/> GPS: {gps==='live'?'live':gps==='error'?'permission/error':'starting…'}</small>}</div><Button onClick={toggle} disabled={p.verificationStatus!=='approved'} variant={p.online?'danger':'primary'}><Power size={17}/>{p.online?'Go Offline':'Go Online'}</Button></div><div className="stats"><Stat title="Rating" value={p.rating?.toFixed(1)||'5.0'} icon={Star}/><Stat title="Completed trips" value={p.totalTrips||0} icon={ClipboardList}/><Stat title="Vehicle" value={p.vehicleType?.toUpperCase()||'KEKE'} icon={Car}/><Stat title="Wallet" value={formatMoney(wallet)} icon={Wallet}/></div><div className="dashboard-two"><div className="panel"><div className="panel-title"><div><h3>Ride requests</h3><p>Available trips matching your vehicle.</p></div><Link to="/driver/trips">View all <ArrowRight size={15}/></Link></div>{available.slice(0,3).map(t=><div className="request-row" key={t._id}><div className="request-icon"><Navigation/></div><div><b>{t.pickup?.label} → {t.destination?.label}</b><small>{t.rider?.fullName||'Rider'} · {t.tripId}</small></div><strong>{formatMoney(t.fare)}</strong><Button onClick={()=>accept(t._id)} disabled={accepting===t._id}>{accepting===t._id?'Accepting…':'Accept'}</Button></div>)}{!available.length&&<p className="muted">No current trip requests.</p>}</div><div className="panel"><h3>My Vehicle</h3><div className="vehicle-summary"><div className="vehicle-big"><Car/></div><div><b>{p.vehicleModel||'Keke Napep'}</b><small>{p.vehicleColor||'Color not provided'} · {p.plateNumber||'Plate not provided'}</small></div><Badge tone="success">{p.verificationStatus}</Badge></div><Link className="text-link" to="/driver/profile">Manage vehicle <ArrowRight size={15}/></Link></div></div></DriverLayout>
}
